import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import CtaBtn from '../../components/CtaBtn'
import axios from 'axios';
import { useRouter } from 'next/router'

import { Column, Table } from 'react-virtualized';
import 'react-virtualized/styles.css';

export default function Home({records}) {
  const router = useRouter()

  const onApprovalAll = () => {
    console.log('approve all!')
  }

  const onClickRow = (idx, {rowIndex, rowData}) => {
    console.log('onClickRow', idx, rowIndex, rowData)
  }

  return (
    <div className={styles.padding}>
      <Head>
        <title>eyos one Pending Approvals</title>
        <meta name="description" content="Generated by a team of passionate individual" />
      </Head>
   
      <div style={{display:'flex', flexDirection:"row", width: 920, justifyContent:"space-between", alignItems:'center', marginBottom:20}}>
        <h4 className={styles.title} style={{marginTop: 0, margin:0}}>Stores Pending Approval</h4>
        <CtaBtn title={'Approve All'} type={'btnApprove'} style={{width:120}} onClick={onApprovalAll}/>
      </div>

      <Table
        headerHeight={40}
        width={920}
        height={400}
        rowHeight={40}
        rowGetter={({ index }) => records[index]}
        rowCount={records.length}
        headerStyle={{
          fontWeight: 500,
          color: 'rgb(13, 12, 56)',
          fontSize: 10, backgroundColor:'rgb(240, 240, 240)', margin: 0, 
          height: 40, display:"flex", alignItems:'center', paddingLeft: 10, justifyContent:'flex-start'
        }}
        rowStyle={{borderBottom: '1px solid rgb(222, 222, 223)'}}
      >
        <Column label='Store Name' dataKey='STORE_NAME' width={300} className={styles.columnRow}/>
        <Column label='Total Tills' dataKey='STORE_TILL_COUNT' width={180}className={styles.columnRow}/>
        <Column label='Store Address' dataKey='STORE_ADDRESS' width={400} className={styles.columnRow}/>
        <Column label='Contact Number' dataKey='STORE_OWNER_MOBILE' width={300} className={styles.columnRow}/>

        <Column width={200} dataKey={''} className={styles.columnRow} 
          headerRenderer={() => <div></div>}
          cellRenderer={(e) => (<CtaBtn title={'View'} type={'btnWarning'} onClick={() => onClickRow(0, e)}/>)}
        />

        <Column width={200} dataKey={''} className={styles.columnRow} 
          headerRenderer={() => <div></div>}
          cellRenderer={(e) => (<CtaBtn title={'Reject'} type={'btnReject'}onClick={() => onClickRow(1, e)}/>)}
        />

        <Column width={200} dataKey={''} className={styles.columnRow} 
          headerRenderer={() => <div></div>}
          cellRenderer={(e) => (<CtaBtn title={'Approve'} type={'btnApprove'} onClick={() => onClickRow(2, e)}/>)}
        />
      </Table>
  
    </div>
  )
}


export async function getStaticProps(context) {
  const {data} = await axios.get('https://tardjf.deta.dev/stores')
  const {records} = data
  const filterRecords = records.filter(e => !e.IS_APPROVED)

  return {
    props: { records: filterRecords }
  }
}