import Head from 'next/head'
import axios from 'axios';
import Card from '../../components/Card';

export default function Home({records}) {
  return (
    <>
      <Head>
        <title>eyos one dashboard</title>
        <meta name="description" content="Generated by a team of passionate individual" />
      </Head>
  
    </>
  )
}


export async function getServerSideProps(context) {
  const {data} = await axios.get('https://tardjf.deta.dev/stores')
  const {records} = data

  return {
    props: { records }
  }
}