import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Card from '../components/Card';
import CtaBtn from '../components/CtaBtn'
import axios from 'axios';
import { useRouter } from 'next/router'

export default function Home({records}) {
  const router = useRouter()

  const onClickViewNow = () => {
    router.push('/Merchants/Pending')
  }

  return (
    <div className={styles.padding}>
      <Head>
        <title>eyos one dashboard</title>
        <meta name="description" content="Generated by a team of passionate individual" />
      </Head>
    
      {records > 0 && 
        <div style={{
          display:'flex', flexDirection:'row', border:'1px solid red', width:'100%', 
          justifyContent:"center", alignItems:'center', padding:10, borderRadius: 10, 
          backgroundColor:'rgba(255, 3, 3, 0.1)'
        }}>
          <span style={{width:'100%', color:'red', fontWeight:500, fontSize: 14}}>{records} Stores are awaiting approval</span>
          <CtaBtn title={'View Now'} type={'btnDanger'} onClick={onClickViewNow}/>
        </div>
      }

      <h4 className={styles.title}>Dashboard</h4>
      <div style={{display:'flex', flexDirection:'row', flexWrap:"wrap"}}>
        <Card
          current={'40'}
          increaseBy={10} 
          title={'Stores Onboarded This Week'}
        />
        <Card
          current={'2,021'}
          increaseBy={10} 
          title={'Active Stores'}
        />
        <Card
          current={'20'}
          increaseBy={10} 
          title={'Newly Installed Stores'}
        />
      </div>
    </div>
  )
}


export async function getStaticProps(context) {
  const {data} = await axios.get('https://tardjf.deta.dev/stores')
  const {records} = data
  const filterRecords = records.filter(e => !e.IS_APPROVED && e.STORE_NAME)
  console.log({records, filterRecords})
  return {
    props: { records: filterRecords.length }
  }
}